### ISSUE TITLE
menu-submenu-inline misused

### ISSUE THREAD

**Issue by weimengxi** [g-bbfe/component-navigation#1]
https://github.com/g-bbfe/component-navigation/blob/1141d0b48bedc4e1ca47183aa9f64c9c9c7e7c36/src/www/business/apps/navigation/menu/view.js#L22

menu-submenu-inline 是想表达没脱离父菜单项的包含块， 比如二级菜单目前是在父菜单的包含块内， 三级菜单绝对定位脱离二级子菜单项的包含块。

解决方案： 菜单的模式跟层级有较强关联性， 需要给每个节点添加level属性。@Jack-X-Yang

**Comment by Jack-X-Yang** [comment]
现在在生成状态树的时候会给每个节点添加level字段
根结点的层级为0
