### ISSUE TITLE
Failed render menu tree when url is invalid  

### ISSUE THREAD

**Issue by weimengxi** [g-bbfe/component-navigation#2]
初始路径非法， 找不到节点并不代表树是非法的， 
不应该阻塞菜单树的渲染

@Jack-X-Yang

**Comment by Jack-X-Yang** [comment]
问题原因：
当传入错误的URL时找不到对应的节点，然后不对状态树进行操作，没有调用渲染函数

解决方案：
传入错误的URL也调用渲染函数
